import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.0.5',
  date: '2022-12-16T12:33:29.671Z',
};
export default meta;
